env:
  commonjs: true
  es6: true
  node: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  #  project global variable
  config: false
  #  mocha global variables
  describe: false
  it: false
  before: false
  after: false
  beforeEach: false
  afterEach: false
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  no-unsafe-finally: 0
  import/no-absolute-path: 0
  space-before-function-paren: ["error", {"asyncArrow": "always","anonymous": "never","named": "never"}]
  semi: [2, "always"]
